env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - import
  - "@stylistic"
  - react

rules:
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  react/react-in-jsx-scope: 0
  no-underscore-dangle: [2, { allow: ["__filename", "__dirname"] }]
  react/function-component-definition: [2, { namedComponents: "arrow-function" }]
  react/jsx-filename-extension: [1, { extensions: [".js", ".jsx"] }]
  '@stylistic/semi': ['error', 'always']
  no-unused-vars: ["error", { varsIgnorePattern: "^React$" }]
  multiline-ternary: [0]  # Отключаем принудительные переносы
  react/jsx-closing-bracket-location: [1, "line-aligned"]
  '@stylistic/arrow-parens': ['error', 'always']